/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mpos_sdk_MposSDK */

#ifndef _Included_com_mpos_sdk_MposSDK
#define _Included_com_mpos_sdk_MposSDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    initMethodID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mpos_sdk_MposSDK_initMethodID
  (JNIEnv *, jclass);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    initEnv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mpos_sdk_MposSDK_initEnv
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    download
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mpos_sdk_MposSDK_download
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mpos_sdk_MposSDK_release
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    getTermSn
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_mpos_sdk_MposSDK_getTermSn
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    getTermExtSN
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mpos_sdk_MposSDK_getTermExtSN
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    getTermVerInfo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mpos_sdk_MposSDK_getTermVerInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    getTerminalInfo
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mpos_sdk_MposSDK_getTerminalInfo
  (JNIEnv *, jobject);

/*
 * Class:     com_mpos_sdk_MposSDK
 * Method:    isUpdate
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_mpos_sdk_MposSDK_isUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
