/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pax_service_download_impl_Downloader */

#ifndef _Included_com_pax_service_download_impl_Downloader
#define _Included_com_pax_service_download_impl_Downloader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    initMethodID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_initMethodID
  (JNIEnv *, jclass);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    initEnv
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_initEnv
  (JNIEnv *, jobject);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    download
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_download
  (JNIEnv *, jobject);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_pax_service_download_impl_Downloader_release
  (JNIEnv *, jobject);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    getTermSN
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_getTermSN
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    getTermExtSN
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_getTermExtSN
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    getTermVerInfo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_getTermVerInfo
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_pax_service_download_impl_Downloader
 * Method:    getTerminalInfo
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_pax_service_download_impl_Downloader_getTerminalInfo
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
