#ifndef PAX_MPOS_PROTIMS_GLOBAL_H_
#define PAX_MPOS_PROTIMS_GLOBAL_H_




#ifndef NULL
#ifdef __cplusplus
	#define NULL    0
#else
	#define NULL    ((void *)0)
#endif // __cplusplus
#endif // NULL

enum APPLICATION_ERR_CODE
{
	PROTIMS_SUCCESS = 0,

	PROTIMS_MODEM_BASE  = 100,
	PROTIMS_MODEMCHECK,
	PROTIMS_MODEMDIAL,
	PROTIMS_MODEMTXD,
	PROTIMS_MODEMRESET,
	PROTIMS_MODEMSAYNCGET,
	PROTIMS_ONHOOK,
	PROTIMS_MODEM_END,

	PROTIMS_MPOS_COMM_BASE = 200,
	PROTIMS_MPOS_COMM_END,

	PROTIMS_TCP_BASE    = 300,
	PROTIMS_ROUTERSETDEFAULT,
	PROTIMS_DHCPSTART,
	PROTIMS_DHCPCHECK,
	PROTIMS_ETHSET,
	PROTIMS_INIT_COMM,
	PROTIMS_NETSOCKET,
	PROTIMS_NETCONNECT,
	PROTIMS_DNSRESLOVE,
	PROTIMS_SOCKETADDSET,
	PROTIMS_NETSEND,
	PROTIMS_NETRECV,
	PROTIMS_NETCLOSESOCKET,
	PROTIMS_TCP_END,

	PROTIMS_PPP_BASE    = 400,
	PROTIMS_PPP_END,

	PROTIMS_WNET_BASE   = 500,
	PROTIMS_WIRELESS_END,

	PROTIMS_COMM_BASE  = 600,
	PROTIMS_COMM_END,

	PROTIMS_FILE_OPERATE = 700,
	PROTIMS_FILE_END,

	PROTIMS_UPDATE_ERR_BASE = 800,
	PROTIMS_UPDATE_APP,
	PROTIMS_UPDATE_PARA,
	PROTIMS_UPDATE_FONT,
	PROTIMS_UPDATE_MONITOR,
	PROTIMS_UPDATE_DLL,
	PROTIMS_UPDATE_DELETE,
	PROTIMS_UPDATE_PUK,
	PROTIMS_UPDATE_PUB,
	PROTIMS_UPDATE_END,

	PROTIMS_UPLOAD_ERR_BASE = 900,
	PROTIMS_UPLOAD_GET_TERMINFO,
	PROTIMS_UPLOAD_GET_TERMINFOEX,
	PROTIMS_UPLOAD_ERR_END,

	PROTIMS_KEY_DOWNLOAD_BASE = 1000,
	PROTIMS_NO_RSAKEY_ERROR,
	PROTIMS_KEY_VALIDATE_ERROR,
	PROTIMS_RSA_ENCRYPT_ERROR,
	PROTIMS_KEY_NUM_ERROR,
	PROTIMS_KEY_LENGTH_ERROR,
	PROTIMS_KEY_DOWNLOAD_END,

	PROTIMS_INVALID_ERROR_BASE = 1100,
	PROTIMS_INVALID_IP,
	PROTIMS_INVALID_PORT,
	PROTIMS_INVALID_NETMASK,
	PROTIMS_INVALID_GATEWAY,
	PROTIMS_INVALID_LOCALIP,
	PROTIMS_INVALID_DNS,
	PROTIMS_INVALID_LOCALPORT,
	PROTIMS_INVALID_COM_BUADRATE_TYPE, // debug new
	PROTIMS_INVALID_ERROR_END,

	PROTIMS_PROTOCOL_ERROR_BASE = 1200,
	PROTIMS_PROTOCOL_ERROR_END,
	
	PROTIMS_DWORDTOSTRING = 1300,
	PROTIMS_lOAD_LANG_FAIL,
	PROTIMS_DOWNLOAD_FAIL,
	PROTIMS_COMPARE_BABYLOG_INVALID_PARA_ERROR,
	PROTIMS_SET_TASK_TEN_MORE,
	PROTIMS_FORGET_SET_TASK,
	PROTIMS_FILENO_NOT_SAME,

	PROTIMS_XML_NONE_BASE = 1400,	
	PROTIMS_XML_NONE_END,

	PROTIMS_MPOS_BASE = 1500,
	PROTIMS_MPOS_END,
	
	PROTIMS_COMPRESS_BASE = 1600,
	PROTIMS_COMPRESS_END,

	PROTIMS_UNKNOWN_BASE = 10000
};

#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "errcode.h"
#include "xml.h"
#include "mpos.h"
#include "util.h"
#include "file.h"
#include "des.h"
#include "compress.h"

#endif // PAX_MPOS_PROTIMS_GLOBAL_H_
